
version: "3"
services:
  database:
    image: "mysql:${MYSQL_VERSION}"
    volumes:
      - data:/var/lib/mysql
      - my_data:/app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "${DB_PORT}:3306"
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - "${SERVER_PORT}:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: "database:${DB_PORT}"
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: "${DB_NAME}"
volumes:
  data: {}