
version: "3"
services:
  pre-built:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
  build-from-Dockerfile:
    build: .
    environment:
      MYSQL_ROOT_PASSWORD: root
  build-with-options:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        dockerfile_author: docker
        ARG_APP_VERSION: 5.0.3


