version: "3"
services:
  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8121:3306"
  wordpress:
    depends_on:
      - database
    image: wordpress:latest
    ports:
      - "8120:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: database:8121
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: db